name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          mkdir ~/.ssh

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo ${SSH_PRIVATE_KEY} >> ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          ssh-keyscan -p 10413 -H ${REMOTE_HOST} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "Kopiowanie katalogu dist na serwer zdalny..."
          scp -i key.private -v -P 10413 -r src "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
