name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo ${SSH_PRIVATE_KEY} >> key.private
          cat key.private

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "Kopiowanie katalogu dist na serwer zdalny..."
          scp -i key.private -P 10413 -r src "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
