name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: create .ssh folder
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir /home/runner/.ssh
          echo ${{ secrets.SSH_PRIVATE_KEY }} > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
          chmod 700 /home/runner/.ssh

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "Kopiowanie katalogu dist na serwer zdalny..."
          scp -v -P 10413 -r src "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
