name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add  SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add server to known_hosts
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          ssh-keyscan -p 10413 -H ${REMOTE_HOST} >> ~/.ssh/known_hosts

      

      - name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "Kopiowanie katalogu dist na serwer zdalny..."
          ls -la .
          pwd
          scp -v -P 10413 -r * "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
